# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               myxxxme's blog
tagline:             'Front-end, Back-end Dev Engineer'
description:         'Stay Hungry, Stay Foolish '
url:                 https://myungeunlee.github.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              MYUNG EUN LEE
  url:               https://myungeunlee.github.com
  email:             myeongdms55@gmail.com

# Custom vars
version:             1.0.0

plugins: [jekyll-paginate]

# Tag setting
#collections:
#  tags:
#    output: true
#    permalink: /tags/:path/

#defaults:
#  - scope:
#      path: ''
#      type: tags
#    values:
#      layout: tag

google_analytics:
  ua: 'UA-109898110-1'

github:
  repo: 'https://github.com/myungeunlee'

category_dir: category/
tag_dir: tag/

excerpt_separator: ""
