# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               hoisharka's blog
tagline:             'Front-end Dev Engineer'
description:         '웹 개발자 김태헌입니다.'
url:                 https://hoisharka.github.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              KIM TAE HEON
  url:               https://hoisharka.github.com
  email:             hoisharka@gmail.com

# Custom vars
version:             1.0.0

plugins: [jekyll-paginate]

# Tag setting
#collections:
#  tags:
#    output: true
#    permalink: /tags/:path/

#defaults:
#  - scope:
#      path: ''
#      type: tags
#    values:
#      layout: tag

google_analytics:
  ua: 'UA-109898110-1'

github:
  repo: 'https://github.com/hoisharka/hoisharka.github.io'

category_dir: category/
tag_dir: tag/

excerpt_separator: ""
